description: |
  Basically, you need to set the header 'Authorization' to 'Bearer <API_KEY>'. If you're having trouble with this, email a friend.
type: x-bearer
describedBy: 
  headers: 
    Authorization: 
