#%RAML 0.8
title: Uber user activity
version: v1.2
baseUri: https://sandbox-api.uber.com/{version}
securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth_2_0.raml
  - basic: !include securitySchemes/basic.raml
schemas:
  - userHistoryResponse: !include /schemas/userHistoryResponse-schema.json
/history: 
  description: |
    The User Activity endpoint returns a limited amount of data about a user's lifetime activity with Uber. The response will include pickup and dropoff times, the city the trips took place in, the distance of past requests, and information about which products were requested.
    
    The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
  get: 
    description: |
      The User Activity endpoint returns a limited amount of data about a user's lifetime activity with Uber. The response will include pickup and dropoff times, the city the trips took place in, the distance of past requests, and information about which products were requested.
      
      The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
    queryParameters: 
      offset: 
        description: Offset the list of returned results by this amount. Default is zero.
        type: integer
        required: true
        default: 0
        example: 2
      limit: 
        description: Number of items to retrieve. Default is 5, maximum is 50.
        type: integer
        required: true
        default: 5
        example: 20
    responses: 
      200: 
        body: 
          application/json: 
            schema: userHistoryResponse
            example: !include examples/userHistoryResponse-example.json
documentation: 
  - title: Headline
    content: !include docs/userActivity/headline.md
