queryParameters: 
  end_latitude: 
    description: Latitude component of end location.
    required: true
  end_longitude: 
    description: Longitude component of end location.
    required: true
  start_latitude: 
    description: Latitude component of start location.
    required: true
  start_longitude: 
    description: Longitude component of start location.
    required: true
